#!/bin/bash
export GENTOO_PLATFORM="${GENTOO_PLATFORM:-"amd64"}"

export GENTOO_BOOT_ISO_ID="${GENTOO_BOOT_ISO_ID:-"install-${GENTOO_PLATFORM}-minimal"}"
export GENTOO_PORTAGE_ID="${GENTOO_PORTAGE_ID:-"portage"}"
export GENTOO_STAGE3_ID="${GENTOO_STAGE3_ID:-"stage3-${GENTOO_PLATFORM}"}"

# TODO remove when the locate feature is added.
export GENTOO_BOOT_ISO=${GENTOO_BOOT_ISO:-"./install-amd64-minimal.iso"}
export GENTOO_PORTAGE=${GENTOO_PORTAGE:-"./portage.tar.xz"}
export GENTOO_STAGE3=${GENTOO_STAGE3:-"./stage3-amd64.tar.xz"}

export GENTOO_FILES=${GENTOO_FILES:-"${VBOX_FILE_BASE}/gentoo_files"}

# plus the default
export BOOT_ISO=${GENTOO_BOOT_ISO}
export VBOX_NAME=${VBOX_NAME:-"gentoo_vm"}
